# Generated by Django 4.2.30 on 2026-07-22 10:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Office",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome Ufficio"
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="Codice"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Descrizione"),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=7, null=True, verbose_name="Colore HEX"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Icona Lucide",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Attivo")),
            ],
            options={
                "verbose_name": "Ufficio",
                "verbose_name_plural": "Uffici",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="Telefono"
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="members",
                        to="accounts.office",
                        verbose_name="Ufficio",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Profilo Utente",
                "verbose_name_plural": "Profili Utenti",
            },
        ),
        migrations.CreateModel(
            name="OfficeFieldPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=50, verbose_name="Modello")),
                ("field_name", models.CharField(max_length=50, verbose_name="Campo")),
                (
                    "permission_type",
                    models.CharField(
                        choices=[
                            ("READ", "Sola Lettura"),
                            ("WRITE", "Lettura e Scrittura"),
                        ],
                        max_length=5,
                        verbose_name="Tipo Permesso",
                    ),
                ),
                (
                    "office",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="field_permissions",
                        to="accounts.office",
                        verbose_name="Ufficio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Permesso Campo",
                "verbose_name_plural": "Permessi Campi",
                "ordering": ["office", "model_name", "field_name"],
                "unique_together": {("office", "model_name", "field_name")},
            },
        ),
    ]
