# Generated by Django 4.2.30 on 2026-07-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="machine",
            name="matricola",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Matricola"
            ),
        ),
        migrations.AlterField(
            model_name="machineadmindocument",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("FATTURA", "Fattura"),
                    ("BOLLA_TRASPORTO", "Bolla di Trasporto"),
                    ("ORDINE_ACQUISTO", "Ordine di Acquisto"),
                    ("COPIA_PAGAMENTO", "Copia Pagamento"),
                    ("PERIZIA_CONSULENTE", "Perizia consulente"),
                    ("ALTRO_ADMIN", "Altro"),
                ],
                max_length=30,
                verbose_name="Tipo Documento",
            ),
        ),
    ]
