# Generated by Django 4.2.30 on 2026-07-22 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0002_alter_machine_matricola_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="machine",
            options={
                "ordering": ["cdl", "cc"],
                "verbose_name": "Macchinario",
                "verbose_name_plural": "Macchinari",
            },
        ),
        migrations.RemoveField(
            model_name="machine",
            name="matricola",
        ),
        migrations.AddField(
            model_name="machine",
            name="cc",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CC"
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="cdl",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="CDL"
            ),
        ),
    ]
