# Generated by Django 6.0.7 on 2026-07-24 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0003_alter_machine_options_remove_machine_matricola_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="tipo_macchina",
            field=models.CharField(
                choices=[
                    ("COMPLESSA", "Macchina complessa"),
                    ("ACQUISTO_DIRETTO", "Macchina ad acquisto diretto"),
                ],
                default="COMPLESSA",
                max_length=30,
                verbose_name="Tipo Macchina",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="stato",
            field=models.CharField(
                choices=[
                    ("in_costruzione", "In costruzione"),
                    ("attiva", "Attiva"),
                    ("in_manutenzione", "In Manutenzione"),
                    ("ferma", "Ferma"),
                    ("dismessa", "Dismessa"),
                ],
                default="in_costruzione",
                max_length=20,
                verbose_name="Stato",
            ),
        ),
        migrations.AlterField(
            model_name="machinedocument",
            name="tipo_documento",
            field=models.CharField(
                choices=[
                    ("BOLLA_TRASPORTO", "Documento di Trasporto"),
                    ("USO_MANUTENZIONE", "Manuale Uso e Manutenzione"),
                    ("CERTIFICAZIONE_CE", "Certificazione CE"),
                    ("SCHEDA_VDR", "Scheda VDR"),
                    ("VERBALE_COLLAUDO", "Verbale di Collaudo"),
                    ("ALTRO", "Altro"),
                ],
                max_length=30,
                verbose_name="Tipo Documento",
            ),
        ),
        migrations.CreateModel(
            name="MachineChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("codice", models.CharField(max_length=80)),
                ("descrizione", models.CharField(max_length=200)),
                (
                    "ufficio",
                    models.CharField(
                        choices=[("TECH", "Ufficio Tecnico"), ("IT", "Ufficio IT")],
                        max_length=10,
                    ),
                ),
                ("ordine", models.PositiveIntegerField(default=0)),
                ("document_types", models.JSONField(blank=True, default=list)),
                ("solo_visualizzazione_tech", models.BooleanField(default=False)),
                ("completata", models.BooleanField(default=False)),
                ("completata_at", models.DateTimeField(blank=True, null=True)),
                (
                    "completata_da",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="completed_checklist_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checklist_items",
                        to="machines.machine",
                    ),
                ),
            ],
            options={
                "ordering": ["ufficio", "ordine", "id"],
                "unique_together": {("machine", "codice")},
            },
        ),
        migrations.AddField(
            model_name="machinedocument",
            name="checklist_items",
            field=models.ManyToManyField(
                blank=True, related_name="documents", to="machines.machinechecklistitem"
            ),
        ),
    ]
