# Generated by Django 6.0.7 on 2026-07-24 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0006_machine_commessa_machine_commessa_automazione_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MachineFiscalBenefit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "attivo",
                    models.BooleanField(default=False, verbose_name="Beneficio attivo"),
                ),
                (
                    "chiuso",
                    models.BooleanField(default=False, verbose_name="Beneficio chiuso"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Creazione"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Ultimo Aggiornamento"
                    ),
                ),
                (
                    "machine",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="benefit_fiscal",
                        to="machines.machine",
                    ),
                ),
            ],
            options={
                "verbose_name": "Beneficio Fiscale",
                "verbose_name_plural": "Benefici Fiscali",
            },
        ),
        migrations.CreateModel(
            name="MachineFiscalBenefitDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "operation",
                    models.CharField(
                        choices=[
                            ("fatture", "Fatture"),
                            ("documenti_trasporto", "Documenti di trasporto"),
                            ("ordini_acquisto", "Ordini di acquisto"),
                            ("contabili_pagamento", "Contabili di pagamento"),
                            ("perizia_asseverata", "Perizia asseverata"),
                            ("attestazione_contabile", "Attestazione contabile"),
                            ("comunicazione_preventiva", "Comunicazione preventiva"),
                            ("comunicazione_intermedia", "Comunicazione intermedia"),
                            ("comunicazione_consuntivo", "Comunicazione a consuntivo"),
                        ],
                        max_length=40,
                        verbose_name="Operazione",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/fiscal_benefit/", verbose_name="File"
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data Upload"),
                ),
                (
                    "benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="machines.machinefiscalbenefit",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fiscal_benefit_docs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Caricato da",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Beneficio Fiscale",
                "verbose_name_plural": "Documenti Beneficio Fiscale",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="MachineFiscalBenefitMaintenanceYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anno", models.IntegerField(verbose_name="Anno")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Data Creazione"
                    ),
                ),
                (
                    "benefit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maintenance_years",
                        to="machines.machinefiscalbenefit",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anno Mantenimento",
                "verbose_name_plural": "Anni Mantenimento",
                "ordering": ["anno"],
            },
        ),
        migrations.CreateModel(
            name="MachineFiscalBenefitMaintenanceDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="documents/fiscal_benefit/maintenance/",
                        verbose_name="File",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Data Upload"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="maintenance_docs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Caricato da",
                    ),
                ),
                (
                    "year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="machines.machinefiscalbenefitmaintenanceyear",
                    ),
                ),
            ],
            options={
                "verbose_name": "Documento Mantenimento",
                "verbose_name_plural": "Documenti Mantenimento",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
