# Generated by Django 5.2 on 2026-07-29 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0007_machinefiscalbenefit_machinefiscalbenefitdocument_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='consulente',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Consulente'),
        ),
        migrations.AddField(
            model_name='machine',
            name='data_interconnessione_prevista',
            field=models.DateField(blank=True, null=True, verbose_name='Data Interconnessione Prevista'),
        ),
        migrations.AddField(
            model_name='machine',
            name='id_investimento_consulente',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Investimento Consulente'),
        ),
        migrations.AddField(
            model_name='machine',
            name='id_investimento_rm',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID Investimento RM'),
        ),
        migrations.AddField(
            model_name='machine',
            name='interconnessione_prevista',
            field=models.BooleanField(blank=True, null=True, verbose_name='Interconnessione Prevista'),
        ),
        migrations.AddField(
            model_name='machine',
            name='interconnessione_stato',
            field=models.CharField(choices=[('non_interconnesso', 'Non interconnesso'), ('in_attesa', 'In attesa di interconnessione'), ('interconnessa', 'Interconnessa')], default='non_interconnesso', max_length=20, verbose_name='Stato Interconnessione'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='stato',
            field=models.CharField(choices=[('inserimento_db', 'Inserimento nel database'), ('ordinata', 'Ordinata'), ('in_costruzione', 'In costruzione'), ('attiva', 'Attiva'), ('in_manutenzione', 'In Manutenzione'), ('ferma', 'Ferma'), ('dismessa', 'Dismessa')], default='inserimento_db', max_length=20, verbose_name='Stato'),
        ),
        migrations.AlterField(
            model_name='machinedocument',
            name='tipo_documento',
            field=models.CharField(choices=[('BOLLA_TRASPORTO', 'Documento di Trasporto'), ('USO_MANUTENZIONE', 'Manuale Uso e Manutenzione'), ('CERTIFICAZIONE_CE', 'Certificazione CE'), ('SCHEDA_VDR', 'Scheda VDR'), ('VERBALE_COLLAUDO', 'Verbale di Collaudo'), ('ORDINE_MACCHINA', 'Ordine Macchina'), ('ALTRO', 'Altro')], max_length=30, verbose_name='Tipo Documento'),
        ),
    ]
