# Generated by Django 5.2 on 2026-07-29 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0008_machine_consulente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machinestatuslog',
            name='fermi_macchina',
        ),
        migrations.RemoveField(
            model_name='machinestatuslog',
            name='motivo_fermo',
        ),
        migrations.RemoveField(
            model_name='machinestatuslog',
            name='orario_fermo',
        ),
        migrations.RemoveField(
            model_name='machinestatuslog',
            name='pezzi_buoni',
        ),
    ]
