# Generated by Django 5.2 on 2026-07-29 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0009_remove_machinestatuslog_fermi_macchina_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='stabilimento',
            field=models.CharField(blank=True, choices=[('Campitello', 'Campitello'), ('Tubificio', 'Tubificio'), ('Pilastro', 'Pilastro')], max_length=50, null=True, verbose_name='Stabilimento'),
        ),
    ]
