# Generated by Django 5.2 on 2026-07-29 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0010_machine_stabilimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='commessa',
            field=models.JSONField(blank=True, default=list, verbose_name='Commessa'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='commessa_automazione',
            field=models.JSONField(blank=True, default=list, verbose_name='Commessa Automazione'),
        ),
        migrations.AlterField(
            model_name='machine',
            name='commessa_macchina',
            field=models.JSONField(blank=True, default=list, verbose_name='Commessa Macchina'),
        ),
    ]
