# Generated by Django 5.2 on 2026-07-29 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machines', '0011_alter_machine_commessa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='stato',
            field=models.CharField(choices=[('inserimento_db', 'Inserimento nel database'), ('ordinata', 'Ordinata'), ('in_costruzione', 'In costruzione'), ('attiva', 'Attiva'), ('in_manutenzione', 'In Manutenzione'), ('ferma', 'Ferma')], default='inserimento_db', max_length=20, verbose_name='Stato'),
        ),
    ]
