# Generated by Django 5.2 on 2026-07-02 18:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricola', models.CharField(max_length=50, unique=True, verbose_name='Matricola')),
                ('capannone', models.CharField(max_length=50, verbose_name='Capannone')),
                ('anno_avviamento', models.IntegerField(blank=True, null=True, verbose_name='Anno di Avviamento')),
                ('stato', models.CharField(choices=[('attiva', 'Attiva'), ('in_manutenzione', 'In Manutenzione'), ('ferma', 'Ferma'), ('dismessa', 'Dismessa')], default='attiva', max_length=20, verbose_name='Stato')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Creazione')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
            ],
            options={
                'verbose_name': 'Macchinario',
                'verbose_name_plural': 'Macchinari',
                'ordering': ['matricola'],
            },
        ),
        migrations.CreateModel(
            name='MachineAdminDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('FATTURA', 'Fattura'), ('BOLLA_TRASPORTO', 'Bolla di Trasporto'), ('ORDINE_ACQUISTO', 'Ordine di Acquisto'), ('COPIA_PAGAMENTO', 'Copia Pagamento'), ('ALTRO_ADMIN', 'Altro')], max_length=30, verbose_name='Tipo Documento')),
                ('numero_documento', models.CharField(max_length=50, verbose_name='Numero Documento')),
                ('data_documento', models.DateField(verbose_name='Data Documento')),
                ('importo', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Importo €')),
                ('fornitore', models.CharField(blank=True, max_length=200, null=True, verbose_name='Fornitore')),
                ('descrizione', models.TextField(blank=True, null=True, verbose_name='Descrizione')),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/admin/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Upload')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_documents', to='machines.machine')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_admin_docs', to=settings.AUTH_USER_MODEL, verbose_name='Caricato da')),
            ],
            options={
                'verbose_name': 'Documento Amministrativo',
                'verbose_name_plural': 'Documenti Amministrativi',
                'ordering': ['-data_documento'],
            },
        ),
        migrations.CreateModel(
            name='MachineDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(choices=[('USO_MANUTENZIONE', 'Manuale Uso e Manutenzione'), ('CERTIFICAZIONE_CE', 'Certificazione CE'), ('SCHEDA_VDR', 'Scheda VDR'), ('VERBALE_COLLAUDO', 'Verbale di Collaudo'), ('ALTRO', 'Altro')], max_length=30, verbose_name='Tipo Documento')),
                ('nome_file', models.CharField(max_length=255, verbose_name='Nome File')),
                ('file', models.FileField(upload_to='documents/tech/', verbose_name='File')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data Upload')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='machines.machine')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_docs', to=settings.AUTH_USER_MODEL, verbose_name='Caricato da')),
            ],
            options={
                'verbose_name': 'Documento Tecnico',
                'verbose_name_plural': 'Documenti Tecnici',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineITData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_accentratore', models.CharField(blank=True, choices=[('IOX', 'IOX'), ('RIO', 'RIO'), ('PLC', 'PLC')], max_length=10, null=True, verbose_name='Tipo Accentratore')),
                ('indirizzo_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Indirizzo IP')),
                ('note_it', models.TextField(blank=True, null=True, verbose_name='Note IT')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='it_data', to='machines.machine')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='it_updates', to=settings.AUTH_USER_MODEL, verbose_name='Aggiornato da')),
            ],
            options={
                'verbose_name': 'Dati IT Macchinario',
                'verbose_name_plural': 'Dati IT Macchinari',
            },
        ),
        migrations.CreateModel(
            name='MachineStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stato', models.CharField(max_length=20, verbose_name='Stato')),
                ('pezzi_buoni', models.IntegerField(default=0, verbose_name='Pezzi Buoni')),
                ('fermi_macchina', models.IntegerField(default=0, verbose_name='Fermi Macchina')),
                ('orario_fermo', models.DateTimeField(blank=True, null=True, verbose_name='Orario Fermo')),
                ('motivo_fermo', models.CharField(blank=True, max_length=200, null=True, verbose_name='Motivo Fermo')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='machines.machine')),
            ],
            options={
                'verbose_name': 'Log Stato Macchinario',
                'verbose_name_plural': 'Log Stato Macchinari',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='MachineTechData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione_tecnica', models.TextField(blank=True, null=True, verbose_name='Descrizione Tecnica')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('modello', models.CharField(blank=True, max_length=100, null=True, verbose_name='Modello')),
                ('anno_costruzione', models.IntegerField(blank=True, null=True, verbose_name='Anno di Costruzione')),
                ('note_tecniche', models.TextField(blank=True, null=True, verbose_name='Note Tecniche')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Ultimo Aggiornamento')),
                ('machine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tech_data', to='machines.machine')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tech_updates', to=settings.AUTH_USER_MODEL, verbose_name='Aggiornato da')),
            ],
            options={
                'verbose_name': 'Dati Tecnici Macchinario',
                'verbose_name_plural': 'Dati Tecnici Macchinari',
            },
        ),
    ]
