# Generated by Django 6.0.7 on 2026-07-23 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0003_alter_machine_options_remove_machine_matricola_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FaseCostruzione",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("ordine", models.IntegerField(default=0)),
                (
                    "tipo_macchina_applicabile",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("COMPLESSA", "Complessa"),
                            ("DIRETTA", "Acquisto Diretto"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="machinestatuslog",
            name="motivo_fermo",
        ),
        migrations.RemoveField(
            model_name="machinestatuslog",
            name="orario_fermo",
        ),
        migrations.AddField(
            model_name="machine",
            name="fase_operativa",
            field=models.CharField(
                choices=[
                    ("COSTRUZIONE", "In Costruzione"),
                    ("PRODUZIONE", "In Produzione"),
                ],
                default="COSTRUZIONE",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="tipo_acquisizione",
            field=models.CharField(
                choices=[("COMPLESSA", "Complessa"), ("DIRETTA", "Acquisto Diretto")],
                default="DIRETTA",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="MacchinaFase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("completata", models.BooleanField(default=False)),
                ("data_completamento", models.DateTimeField(blank=True, null=True)),
                (
                    "fase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="machines.fasecostruzione",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fasi_costruzione",
                        to="machines.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DocumentoFase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome_documento", models.CharField(max_length=100)),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="fasi_costruzione/"
                    ),
                ),
                ("completato", models.BooleanField(default=False)),
                (
                    "macchina_fase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documenti",
                        to="machines.macchinafase",
                    ),
                ),
            ],
        ),
    ]
