# Generated by Django 6.0.7 on 2026-07-23 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "machines",
            "0004_fasecostruzione_remove_machinestatuslog_motivo_fermo_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="fasecostruzione",
            name="ufficio_competente",
            field=models.CharField(
                choices=[("TECH", "Ufficio Tecnico"), ("IT", "Ufficio Informatico")],
                default="TECH",
                max_length=10,
            ),
        ),
    ]
