# Generated by Django 6.0.7 on 2026-07-23 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0005_fasecostruzione_ufficio_competente"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="machinedocument",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="machinedocument",
            name="uploaded_by",
        ),
        migrations.RemoveField(
            model_name="machineitdata",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="machineitdata",
            name="updated_by",
        ),
        migrations.RemoveField(
            model_name="machinestatuslog",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="machinetechdata",
            name="machine",
        ),
        migrations.RemoveField(
            model_name="machinetechdata",
            name="updated_by",
        ),
        migrations.AlterModelOptions(
            name="documentofase",
            options={
                "verbose_name": "Documento Fase",
                "verbose_name_plural": "Documenti Fase",
            },
        ),
        migrations.AlterModelOptions(
            name="fasecostruzione",
            options={
                "ordering": ["ordine"],
                "verbose_name": "Fase di Costruzione",
                "verbose_name_plural": "Fasi di Costruzione",
            },
        ),
        migrations.AlterModelOptions(
            name="macchinafase",
            options={
                "ordering": ["fase__ordine"],
                "verbose_name": "Fase Macchina",
                "verbose_name_plural": "Fasi Macchina",
            },
        ),
        migrations.AlterModelOptions(
            name="machine",
            options={
                "verbose_name": "Macchinario",
                "verbose_name_plural": "Macchinari",
            },
        ),
        migrations.AlterField(
            model_name="documentofase",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="documenti_fasi/"),
        ),
        migrations.AlterField(
            model_name="fasecostruzione",
            name="tipo_macchina_applicabile",
            field=models.CharField(
                choices=[
                    ("COMPLESSA", "Macchina Complessa"),
                    ("DIRETTA", "Ad Acquisto Diretto"),
                    ("ENTRAMBE", "Entrambe"),
                ],
                default="ENTRAMBE",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="fasecostruzione",
            name="ufficio_competente",
            field=models.CharField(
                choices=[
                    ("TECH", "Ufficio Tecnico"),
                    ("IT", "Ufficio Informatico"),
                    ("ADMIN", "Amministrazione"),
                ],
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="macchinafase",
            name="fase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="machines.fasecostruzione",
            ),
        ),
        migrations.AlterField(
            model_name="macchinafase",
            name="machine",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="fasi",
                to="machines.machine",
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="anno_avviamento",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="capannone",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="machine",
            name="cc",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Centro di Costo"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="cdl",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Centro di Lavoro"
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="machine",
            name="fase_operativa",
            field=models.CharField(default="in_costruzione", max_length=20),
        ),
        migrations.AlterField(
            model_name="machine",
            name="stato",
            field=models.CharField(
                choices=[
                    ("in_costruzione", "In Costruzione"),
                    ("attiva", "Attiva"),
                    ("ferma", "Ferma"),
                    ("in_manutenzione", "In Manutenzione"),
                    ("dismessa", "Dismessa"),
                ],
                default="in_costruzione",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="tipo_acquisizione",
            field=models.CharField(
                choices=[
                    ("COMPLESSA", "Macchina Complessa"),
                    ("DIRETTA", "Ad Acquisto Diretto"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="machine",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name="MachineAdminDocument",
        ),
        migrations.DeleteModel(
            name="MachineDocument",
        ),
        migrations.DeleteModel(
            name="MachineITData",
        ),
        migrations.DeleteModel(
            name="MachineStatusLog",
        ),
        migrations.DeleteModel(
            name="MachineTechData",
        ),
    ]
