# Generated by Django 6.0.7 on 2026-07-24 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("machines", "0005_move_mes_checklist_item"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="commessa",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Commessa"
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="commessa_automazione",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="Commessa Automazione",
            ),
        ),
        migrations.AddField(
            model_name="machine",
            name="commessa_macchina",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Commessa Macchina"
            ),
        ),
    ]
